src/Entity/Bird.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BirdRepository")
 */
class Bird
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    const BIRD_REIGN = "Animalia";

    const BIRD_PHYLUM = "Chordata";

    const BIRD_CLASS = "Aves";

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $bird_order;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $family;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $vernacularname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $validname;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Image", orphanRemoval=true)
     * @ORM\JoinColumn(nullable=true)
     */
    private $image;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Capture", mappedBy="bird", orphanRemoval=true)
     */
    private $captures;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $cd_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_url;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_thumbnail;

    public function __construct()
    {
        $this->captures = new ArrayCollection();
    }

    /**
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return null|string
     */
    public function getReign(): ?string
    {
        return self::BIRD_REIGN;
    }

    /**
     * @return null|string
     */
    public function getPhylum(): ?string
    {
        return self::BIRD_PHYLUM;
    }

    /**
     * @return null|string
     */
    public function getClass(): ?string
    {
        return self::BIRD_CLASS;
    }

    /**
     * @return null|string
     */
    public function getBirdOrder(): ?string
    {
        return $this->bird_order;
    }

    /**
     * @param string $bird_order
     * @return Bird
     */
    public function setBirdOrder(string $bird_order): self
    {
        $this->bird_order = $bird_order;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getFamily(): ?string
    {
        return $this->family;
    }

    /**
     * @param string $family
     * @return Bird
     */
    public function setFamily(string $family): self
    {
        $this->family = $family;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getVernacularname(): ?string
    {
        return $this->vernacularname;
    }

    /**
     * @param string $vernacularname
     * @return Bird
     */
    public function setVernacularname(string $vernacularname): self
    {
        $this->vernacularname = $vernacularname;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getValidname(): ?string
    {
        return $this->validname;
    }

    /**
     * @param string $validname
     * @return Bird
     */
    public function setValidname(string $validname): self
    {
        $this->validname = $validname;

        return $this;
    }

    /**
     * @param Image|null $image
     */
    public function setImage(Image $image = null)
    {
        $this->image = $image;
    }

    /**
     * @return mixed
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @return Collection|Capture[]
     */
    public function getCaptures(): Collection
    {
        return $this->captures;
    }

    /**
     * @param Capture $capture
     * @return Bird
     */
    public function addCapture(Capture $capture): self
    {
        $this->captures[] = $capture;
        
        $capture->setBird($this);

        return $this;
    }

    /**
     * @param Capture $capture
     * @return Bird
     */
    public function removeCapture(Capture $capture): self
    {
        $this->captures->removeElement($capture);
    }

    public function getCdName(): ?string
    {
        return $this->cd_name;
    }

    public function setCdName(string $cd_name): self
    {
        $this->cd_name = $cd_name;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(?string $image_url): self
    {
        $this->image_url = $image_url;

        return $this;
    }

    public function getImageThumbnail(): ?string
    {
        return $this->image_thumbnail;
    }

    public function setImageThumbnail(?string $image_thumbnail): self
    {
        $this->image_thumbnail = $image_thumbnail;

        return $this;
    }
}

src/Controller/Frontend/BirdController.php
<?php

namespace App\Controller\Frontend;

use App\Entity\Bird;
use App\Services\Bird\NAOBirdManager;
use App\Services\Bird\NAOCountBirds;
use App\Services\Pagination\NAOPagination;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class BirdController extends Controller
{
    /**
     * @Route("repertoire/{page}", defaults={"page"=1}, requirements={"page" = "\d+"}, name="repertory")
     * @param Request $request
     * @param NAOBirdManager $naoBirdManager
     * @param NAOPagination $naoPagination
     * @param NAOCountBirds $naoCountBirds
     * @param $page
     * @return Response
     */
    public function showRepertory(Request $request, NAOBirdManager $naoBirdManager, NAOPagination $naoPagination, NAOCountBirds $naoCountBirds, $page)
    {
        $regions = json_decode(file_get_contents("https://geo.api.gouv.fr/regions"), true);
        $numberOfBirds = $naoCountBirds->countBirds();
        $numberOfBirdsPerPage = $naoPagination->getNbBirdsPerPage();
        $birds = $naoBirdManager->getBirdsPerPage($page, $numberOfBirds, $numberOfBirdsPerPage);
        $nbRepertoryPages = $naoPagination->CountNbPages($numberOfBirds, $numberOfBirdsPerPage);
        $nextPage = $naoPagination->getNextPage($page);
        $previousPage = $naoPagination->getPreviousPage($page);
        if ($request->isMethod('POST')) {
            $region = $request->get('region');
            $letter = $request->get('letter');
            $session = $request->getSession();
            $session->set('region', $region);
            $session->set('letter', $letter);
            return $this->redirectToRoute('result_search_birds');
        }

        return $this->render('bird\repertory.html.twig',
            array(
                'birds' => $birds, 
                'nbRepertoryPages' => $nbRepertoryPages, 
                'nextPage' => $nextPage, 
                'previousPage' => $previousPage,
                'page' => $page,
                'regions' => $regions,
            )); 
    }

        /**
     * @Route("repertoire/{letter}/{page}", defaults={"page"=1}, requirements={"page" = "\d+"}, name="repertory_by_letter")
     * @param $letter
     * @param $page
     * @param NAOBirdManager $naoBirdManager
     * @param NAOPagination $naoPagination
     * @param NAOCountBirds $naoCountBirds
     * @return Response
     */
    public function showRepertoryByLetter($letter, $page, NAOBirdManager $naoBirdManager, NAOPagination $naoPagination, NAOCountBirds $naoCountBirds)
    {
        $numberOfBirds = $naoCountBirds->countBirdsByLetter($letter);
        $numberOfBirdsPerPage = $naoPagination->getNbBirdsPerPage();
        $birds = $naoBirdManager->getBirdsByLetter($letter, $page, $numberOfBirds, $numberOfBirdsPerPage);
        $nbRepertoryPages = $naoPagination->CountNbPages($numberOfBirds, $numberOfBirdsPerPage);
        $nextPage = $naoPagination->getNextPage($page);
        $previousPage = $naoPagination->getPreviousPage($page);
        $regions = json_decode(file_get_contents("https://geo.api.gouv.fr/regions"), true);

        return $this->render('bird\repertory.html.twig',
            array(
                'birds' => $birds, 
                'nbRepertoryPages' => $nbRepertoryPages, 
                'nextPage' => $nextPage, 
                'previousPage' => $previousPage,
                'page' => $page,
                'letter' => $letter,
                'regions' => $regions,
            ));
    }

    /**
     * @Route("resultat-recherche-oiseaux/{page}", defaults={"page"=1}, requirements={"page" = "\d+"}, name="result_search_birds")
     * @param NAOBirdManager $naoBirdManager
     * @param NAOPagination $naoPagination
     * @param NAOCountBirds $naoCountBirds
     * @param $page
     * @param Request $request
     * @return Response
     */
    public function showBirdsByRegion(NAOBirdManager $naoBirdManager, NAOPagination $naoPagination, NAOCountBirds $naoCountBirds, $page, Request $request)
    {
        $regions = json_decode(file_get_contents("https://geo.api.gouv.fr/regions"), true);
        $session = $request->getSession();
        $letter = $session->get('letter');
        $region = $session->get('region');
        $numberOfSearchBirds = $naoCountBirds->countSearchBirdsByRegionAndLetter($region, $letter);
        $numberOfBirdsPerPage = $naoPagination->getNbBirdsPerPage();
        $birds = $naoBirdManager->searchBirdsByRegionAndLetterPerPage($region, $letter, $page, $numberOfSearchBirds, $numberOfBirdsPerPage);
        $nbRepertoryPages = $naoPagination->CountNbPages($numberOfSearchBirds, $numberOfBirdsPerPage);
        $nextPage = $naoPagination->getNextPage($page);
        $previousPage = $naoPagination->getPreviousPage($page);

        return $this->render('bird\repertory.html.twig',
            array
            (
                'birds' => $birds, 
                'nbRepertoryPages' => $nbRepertoryPages, 
                'nextPage' => $nextPage, 
                'previousPage' => $previousPage, 
                'page' => $page, 
                'regions' => $regions, 
                'region' => $region
            ));
    }

    /**
     * @Route("oiseau/{id}", requirements={"id" = "\d+"}, name="bird")
     * @ParamConverter("bird", class="App\Entity\Bird")
     * @param $bird
     * @return Response
     */
    public function showBird(Bird $bird)
    {
        if (!$bird) {
            throw $this->createNotFoundException("Oiseau non trouvé...");
        }

        return $this->render('bird\bird.html.twig', array('bird' => $bird));
    }
}

templates/bird/bird.html.twig
{% extends "layout.html.twig" %}

{% block title %}{% if bird.vernacularname == false %}{{ bird.validname }} {% else %} {{ bird.vernacularname }} {% endif %}{% endblock %}
{% block mapStylesheets %} 
	{{ parent() }}
	<style type="text/css">
		#map{ /* la carte DOIT avoir une hauteur sinon elle n'apparaît pas */
			height:400px;
			position: sticky !important;
		}
	</style>
{% endblock %}

{% block body %}
	<div id="map" data-identifiant={{ bird.id }}>
	</div>
	<div class="btn-container-retour">
	<button class="btn-retour" type="submit" onclick="history.back()">Retour</button>
	</div>
	<section class="global-page-observation">
		<div class="container-partie-1-2">
		<div class="container-partie1">
		<p class="image-bird">{% if bird.imageThumbnail is not null %}
					<img src="{{ bird.imageThumbnail }}" alt="">
                {% else %}
					<img src="{{ asset('default/bird_default.jpg') }}" alt="">
                {% endif %}</p>
		</div>
		<div class="container-partie-2 bird-2">
		<h1>{% if bird.vernacularname == false %}{{ bird.validname }} {% else %} {{ bird.vernacularname }} - {{ bird.validname }}{% endif %}</h1>
		<p>Règne : {{ bird.reign }}</p>
		<p>Classe : {{ bird.class }}</p>
		<p>Ordre : {{ bird.birdOrder }}</p>
		<p>Famille : {{ bird.family }}</p>
		</div>
		</div>
	</section>
{% endblock %}

{% block mapJavascripts %}
	{{ parent() }}
	<script type="text/javascript" src="{{ asset('javascript/maps/showmap.js') }}"></script>
{% endblock %}

templates/bird/repertory.html.twig
{% extends "base.html.twig" %}

{% block title %} Répertoire {% endblock %}

{% block body %}
	<div class="parallax-2">
    <div></div>
    <div class="nao-flottant-2"><p>REPERTOIRE</p></div>
    <div></div>
    </div>
	<section class="repertoire-selection">

		<div class="al">
		<a href="{{ path('repertory') }}" class="al">All</a> {% for l in 'a'..'z' %} | <a href="{{ path('repertory_by_letter', {'letter': l}) }}">{{l}}</a> {% endfor %}
		</div>

		<form action="{{ path('repertory') }}" method="post" class="letter-region">
			<select name="letter" id="letter">
				<option disabled selected value="">Lettre</option>
            	{% for l in 'a'..'z' %}
					<option value="{{ l }}">{{ l }}</option>
            	{% endfor %}
			</select>
			<select name="region" id="region" class="repertoire-btn-region">
				<option disabled selected value="">Région</option>
                {% for region in regions %}
					<option value="{{ region.nom|lower }}">{{ region.nom }}</option>
                {% endfor %}
			</select>
			<button type="submit" class="btn-repertoire">Rechercher</button>
		</form>

	</section>
    {% if birds is defined %}
		<div class="container-repertoire">
        {% for bird in birds %}

			<div class="oiseau">
				<div class="photo-oiseau-repertoire">
				{% if bird.imageThumbnail is not null %}
					<img src="{{ bird.imageThumbnail }}" alt="">
                {% else %}
					<img src="{{ asset('default/bird_default.jpg') }}" alt="">
                {% endif %}
				</div>
				<div class="nom-oiseau">
				<a href="{{ path('bird', {id: bird.id}) }}">
                    {% if bird.vernacularname == false %}
                        {{ bird.validname }}
                    {% else %}
                        {{ bird.vernacularname }} - {{ bird.validname }}
                    {% endif %}
				</a>
				</div>
			</div>
        {% endfor %}
		</div>

    {% endif %}
		<div class="pagination-repertoire">
			<ul>
				{% if nbRepertoryPages  > 1 %}
					{% if previousPage > 0 %}
					<p> 
						{% if letter is defined %}
							<a href="/repertoire/{{letter}}/{{previousPage}}"> << </a> 
						{% elseif region is defined  %}
							<a href="/resultat-recherche-oiseaux/{{region}}/{{previousPage}}"> << </a> 
						{% else %}
							<a href="/repertoire/{{previousPage}}"> << </a> 
						{% endif %}
					</p>
				{% endif %}
				{% for i in 1..nbRepertoryPages %}
					{% if i == 1 or ((page-5) < i and i < (page + 5)) or i == nbRepertoryPages %}
					{% if i == nbRepertoryPages and page < (nbRepertoryPages - 5) %} <p> ... </p> {% endif %}
					<li {% if page == i %} class="active" {% endif %}>
						{% if letter is defined %}
							<a href="/repertoire/{{letter}}/{{i}}"> {{i}} </a>
						{% elseif region is defined  %}
							<a href="/resultat-recherche-oiseaux/{{region}}/{{i}}"> {{i}} </a>
						{% else %}
							<a href="/repertoire/{{i}}"> {{i}} </a>
						{% endif %}
					</li>
					{% if i == 1 and page > 6 %} <p>...</p> {% endif %}
					{% endif %}
	   			{% endfor %}
	    		<p>
	    			{% if nextPage <= nbRepertoryPages %}
	    				{% if letter is defined %}
	    					<a href="/repertoire/{{letter}}/{{nextPage}}"> >> </a>
	    					{% elseif region is defined  %}
							<a href="/resultat-recherche-oiseaux/{{region}}/{{nextPage}}"> >> </a> 
    					{% else %}
							<a href="/repertoire/{{nextPage}}"> >> </a> 
						{% endif %}
	   				{% endif %}
	   			</p> 
	   		{% endif %}
		</ul>
	</div>
{% endblock %}
{% block javascripts %}{% endblock %}