src/Entity/Capture.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CaptureRepository")
 */
class Capture
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotNull()
     */
    private $content;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotNull()
     */
    private $latitude;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotNull()
     */
    private $longitude;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull()
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $complement;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $region;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull()
     */
    private $zipcode;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull()
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Choice(
     *     choices = { "draft", "published", "validated", "waiting_for_validation" }
     * )
     */
    private $status;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\DateTime()
     */
    private $created_date;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="capture")
     */
    private $comments;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $naturalist_comment;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Bird", inversedBy="captures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $bird;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Image", orphanRemoval=true, cascade={"persist"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="captures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    private $validated_by;

    public function __construct()
    {
        $this->created_date = new \DateTime('now');
        $this->comments = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return null|string
     */
    public function getContent(): ?string
    {
        return $this->content;
    }

    /**
     * @param string $content
     * @return Capture
     */
    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return float|null
     */
    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    /**
     * @param float $latitude
     * @return Capture
     */
    public function setLatitude(float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    /**
     * @return float|null
     */
    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    /**
     * @param float $longitude
     * @return Capture
     */
    public function setLongitude(float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getAddress(): ?string
    {
        return $this->address;
    }

    /**
     * @param string $address
     * @return Capture
     */
    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getComplement(): ?string
    {
        return $this->complement;
    }

    /**
     * @param string|null $complement
     * @return Capture
     */
    public function setComplement(string $complement = null): self
    {
        $this->complement = $complement;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getRegion(): ?string
    {
        return $this->region;
    }

    /**
     * @param string $region
     * @return Capture
     */
    public function setRegion(string $region): self
    {
        $this->region = $region;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    /**
     * @param string $zipcode
     * @return Capture
     */
    public function setZipcode(string $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
     * @param string|null $city
     * @return Capture
     */
    public function setCity(string $city = null): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * @param null|string $status
     * @return Capture
     */
    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }

    /**
     * @param \DateTimeInterface $created_date
     * @return Capture
     */
    public function setCreatedDate(\DateTimeInterface $created_date): self
    {
        $this->created_date = $created_date;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    /**
     * @param Comment $comment
     * @return Capture
     */
    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setCapture($this);
        }

        return $this;
    }

    /**
     * @param Comment $comment
     * @return Capture
     */
    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getCapture() === $this) {
                $comment->setCapture(null);
            }
        }

        return $this;
    }

    /**
     * @return null|string
     */
    public function getNaturalistComment(): ?string
    {
        return $this->naturalist_comment;
    }

    /**
     * @param null|string $naturalist_comment
     * @return Capture
     */
    public function setNaturalistComment(?string $naturalist_comment): self
    {
        $this->naturalist_comment = $naturalist_comment;

        return $this;
    }

    /**
     * @return Bird|null
     */
    public function getBird(): ?Bird
    {
        return $this->bird;
    }

    /**
     * @param Bird|null $bird
     * @return Capture
     */
    public function setBird(?Bird $bird): self
    {
        $this->bird = $bird;

        return $this;
    }

    /**
     * @param Image|null $image
     */
    public function setImage(Image $image = null)
    {
        $this->image = $image;
    }

    /**
     * @return mixed
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @return $this
     */
    public function removeImage()
    {
        $this->image = null;
        return $this;
    }

    /**
     * @return User|null
     */
    public function getUser(): ?User
    {
        return $this->user;
    }

    /**
     * @param User|null $user
     * @return Capture
     */
    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return User|null
     */
    public function getValidatedBy(): ?User
    {
        return $this->validated_by;
    }

    /**
     * @param User|null $validated_by
     * @return Capture
     */
    public function setValidatedBy(?User $validated_by): self
    {
        $this->validated_by = $validated_by;

        return $this;
    }
}

src/Form/Capture/NaturalistCaptureType.php
<?php
// src/Form/Capture/NaturalistCaptureType.php

namespace App\Form\Capture;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use App\Form\Capture\ParticularCaptureType;

class NaturalistCaptureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('status',
                ChoiceType::class,
                array(
                    'label' => "Enregistrer l'observation :",
                    'choices' => array(
                        'Brouillon' => 'draft',
                        'Publié' => 'published',
                    ),
                    'expanded' => true,
                )
            )
        ;
    }

    public function getParent()
    {
        return ParticularCaptureType::class;
    }
}

src/Controller/Frontend/CaptureController.php
<?php

namespace App\Controller\Frontend;

use App\Entity\Capture;
use App\Entity\User;
use App\Entity\Comment;
use App\Entity\Bird;
use App\Services\Comment\NAOCommentManager;
use App\Services\NAOManager;
use App\Services\Capture\NAOCaptureManager;
use App\Services\Comment\NAOCountComments;
use App\Services\Capture\NAOCountCaptures;
use App\Services\Pagination\NAOPagination;
use App\Services\Bird\NAOBirdManager;
use App\Form\Comment\CommentType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class CaptureController extends Controller
{
    /**
     * @Route("observation/{id}", requirements={"id" = "\d+"}, name="capture")
     * @param $id
     * @param Request $request
     * @param NAOManager $naoManager
     * @param NAOCaptureManager $naoCaptureManager
     * @param NAOCountComments $naoCountComments
     * @param ValidatorInterface $validator
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function showCaptureAction($id, Request $request, NAOManager $naoManager, NAOCaptureManager $naoCaptureManager, NAOCountComments $naoCountComments, ValidatorInterface $validator)
    {
        $capture = $naoCaptureManager->getPublishedCapture($id);
        if ($capture === null) {
            return $this->redirectToRoute('observations');
        }
        $numberOfCaptureComments = $naoCountComments->countCapturePublishedComments($capture);
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $user = $this->getUser();
            $comment->setAuthor($user);
            $comment->setCapture($capture);
            $listErrors = $validator->validate($comment);
            if(count($listErrors) > 0) {
                return new Response((string) $listErrors);
            } else {
                $naoManager->addOrModifyEntity($comment);
                $this->addFlash('success',"Commentaire ajouté !");
                return $this->redirectToRoute('capture', ['id' => $capture->getId()]);
            }
        }
        return $this->render('capture\show_capture.html.twig',
            array
            (
                'capture' => $capture,
                'numberOfCaptureComments' => $numberOfCaptureComments,
                'form' => $form->createView(),
            )
        );
    }

    /**
     * @Route("/observations/{pageNumber}", requirements={"pageNumber" = "\d+"}, defaults={"pageNumber"=1}, name="captures")
     * @param Request $request
     * @param NAOCaptureManager $nAOCaptureManager
     * @param NAOCountCaptures $naoCountCaptures
     * @param NAOPagination $naoPagination
     * @param NAOBirdManager $naoBirdManager
     * @param $pageNumber
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function showCapturesAction(Request $request, NAOCaptureManager $nAOCaptureManager, NAOCountCaptures $naoCountCaptures, NAOPagination $naoPagination, NAOBirdManager $naoBirdManager, $pageNumber)
    {
        $regions = json_decode(file_get_contents("https://geo.api.gouv.fr/regions"), true);
        $birds = $this->getDoctrine()->getRepository(Bird::class)->getBirdsByOrderAsc();
        $numberOfPublishedCaptures = $naoCountCaptures->countPublishedCaptures();
        $numberOfPublishedCapturesPerPage = $naoPagination->getNbElementsPerPage();
        $captures = $nAOCaptureManager->getPublishedCapturesPerPage($pageNumber, $numberOfPublishedCaptures, $numberOfPublishedCapturesPerPage);
        $nbCapturesPages = $naoPagination->CountNbPages($numberOfPublishedCaptures, $numberOfPublishedCapturesPerPage);
        $nextPage = $naoPagination->getNextPage($pageNumber);
        $previousPage = $naoPagination->getPreviousPage($pageNumber);
        if ($request->isMethod('POST')) {
            $birdName = $request->get('bird');
            $bird = $naoBirdManager->getBirdByVernacularOrValidName($birdName);
            $region = $request->get('region');
            $session = $request->getSession();
            $session->set('bird', $bird);
            $session->set('region', $region);

            return $this->redirectToRoute('result_search_captures');
        }

        return $this->render('capture\show_captures.html.twig',
            array
            (
                'captures' => $captures, 
                'pageNumber' => $pageNumber, 
                'nbCapturesPages' => $nbCapturesPages, 
                'nextPage' => $nextPage, 
                'previousPage' => $previousPage, 
                'birds' => $birds, 
                'regions' => $regions
            ));
    }

    /**
     * @Route("/resultat-recherche-observations/{pageNumber}", requirements={"pageNumber" = "\d+"}, defaults={"pageNumber"=1}, name="result_search_captures")
     * @param Request $request
     * @param NAOCaptureManager $nAOCaptureManager
     * @param NAOCountCaptures $naoCountCaptures
     * @param NAOPagination $naoPagination
     * @param $pageNumber
     * @return Response
     */
    public function showCapturesSearchAction(Request $request, NAOCaptureManager $nAOCaptureManager, NAOCountCaptures $naoCountCaptures, NAOPagination $naoPagination, $pageNumber)
    {
        $regions = json_decode(file_get_contents("https://geo.api.gouv.fr/regions"), true);
        $birds = $this->getDoctrine()->getRepository(Bird::class)->getBirdsByOrderAsc();
        $resultats = 'résultats';
        $session = $request->getSession();
        $bird = $session->get('bird');
        $region = $session->get('region');
        $numberOfPublishedCapturesPerPage = $naoPagination->getNbElementsPerPage();
        $numberOfSearchCaptures = $naoCountCaptures->countSearchCapturesByBirdAndRegion($bird, $region);
        $capturesSearch =  $nAOCaptureManager->searchCapturesByBirdAndRegionPerPage($bird, $region, $pageNumber, $numberOfSearchCaptures, $numberOfPublishedCapturesPerPage);
        $nbCapturesPages = $naoPagination->CountNbPages($numberOfSearchCaptures, $numberOfPublishedCapturesPerPage);
        $nextPage = $naoPagination->getNextPage($pageNumber);
        $previousPage = $naoPagination->getPreviousPage($pageNumber);

        return $this->render('capture\show_captures.html.twig',
            array
            (
                'captures' => $capturesSearch, 
                'pageNumber' => $pageNumber, 
                'nbCapturesPages' => $nbCapturesPages, 
                'nextPage' => $nextPage, 
                'previousPage' => $previousPage, 
                'birds' => $birds, 
                'regions' => $regions, 
                'resultats' => $resultats
            ));
    }

    /**
     * @Route("/signaler-commentaire/{comment}", requirements={"id" = "\d+"}, name="reported_comment")
     * @ParamConverter("comment", class="App\Entity\Comment")
     * @param Comment $comment
     * @param NAOManager $naoManager
     * @param NAOCommentManager $naoCommentManager
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function reportCommentAction(Comment $comment, NAOManager $naoManager, NAOCommentManager $naoCommentManager, Request $request)
    {
        $referer = $request->headers->get('referer');
        $naoCommentManager->reportComment($comment);
        $naoManager->addOrModifyEntity($comment);
        return $this->redirect($referer);
    }
}

templates/capture/add_image_on_capture.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h1 class="t-index-4">Ajout d'une image sur l'observation {{ capture.id }}</h1>
    <span class="s-t-index-4"></span>

    <div class="container-add">
    <div class="form-add">
    <div class="form-b-add">
    {{ form_start(form, {'attr': {'class': "form-2-add"}}) }}
    {{ form_errors(form) }}
    {{ form_widget(form) }}
    <button type="submit" class="btn-add">Ajouter l'image</button>
    {{ form_end(form) }}
    <a href="{{ path('user_account') }}">Ne pas ajouter d'image</a>
    </div>
    </div>
    </div>
{% endblock %}

templates/capture/add_or_modify_capture.html.twig
{% extends "layout.html.twig" %}

{% block title %}{{ titre }} - Compte {{ userRole }} {% endblock %}

{% block body %}
	<h1>{{ titre }}</h1>
    <h2 id="userRole" data-userrole={{ role }}> Compte {{ userRole }}</h2>
    {% if capture is defined %}
        {% if capture.image is not null %}
            <img src="{{ asset('uploads/bird/' ~ capture.image.filename) }}" alt="" height="150">
            <form action="{{ path('delete_capture_image') }}" method="post">
                <input type="hidden" name="capture" value="{{ capture.id }}">
                <input type="hidden" name="image" value="{{ capture.image.id }}">
                <button type="submit">Supprimer l'image</button>
            </form>
        {% else %}
            <a href="{{ path('add_image_on_capture', {'id': capture.id}) }}">Ajouter une image</a>
        {% endif %}
    {% endif %}
    {{ form_start(form) }}

    {{ form_label(form.bird) }}
    {{ form_errors(form.bird) }}
    {{ form_widget(form.bird) }}

    {{ form_label(form.content) }}
    {{ form_errors(form.content) }}
    {{ form_widget(form.content) }}

    {{ form_label(form.latitude) }}
    {{ form_errors(form.latitude) }}
    {{ form_widget(form.latitude) }}

    {{ form_label(form.longitude) }}
    {{ form_errors(form.longitude) }}
    {{ form_widget(form.longitude) }}

    {{ form_label(form.address) }}
    {{ form_errors(form.address) }}
    {{ form_widget(form.address) }}

    {{ form_label(form.complement) }}
    {{ form_errors(form.complement) }}
    {{ form_widget(form.complement) }}

    {{ form_label(form.zipcode) }}
    {{ form_errors(form.zipcode) }}
    {{ form_widget(form.zipcode) }}

    {{ form_label(form.city) }}
    {{ form_errors(form.city) }}
    {{ form_widget(form.city) }}

    {{ form_label(form.region) }}
    {{ form_errors(form.region) }}
    {{ form_widget(form.region) }}

    {% if is_granted('ROLE_NATURALIST') %}
        {{ form_label(form.status) }}
        {{ form_errors(form.status) }}
        {{ form_widget(form.status) }}
    {% endif %}
    <button type="submit" name="submit" id="{{ role }}_capture_save">{{ titre }}</button>
    {{ form_end(form) }}
{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="{{ asset('javascript/geolocation/geolocation.js') }}"></script>
{% endblock %}
   

templates/capture/show_capture.html.twig
{% extends "layout.html.twig" %}

{% block title %}Observation numéro {{ capture.id }} {% endblock %}

{% block mapStylesheets %}
	{{ parent() }}
	<style type="text/css">
			.capturemap{ /* la carte DOIT avoir une hauteur sinon elle n'apparaît pas */
				height:250px;
				position: sticky !important;

			}
		</style>
{% endblock %}

{% block body %}
	<div id="map0" class="capturemap" data-identifiant={{ capture.id }}>
	</div>
	<div class="btn-container-retour">
	<button class="btn-retour" type="submit" onclick="history.back()">Retour</button>
	</div>
	<div class="global-page-observation">
	<div class="container-global">
	<div class="C-C-p1-p2">
	<div class="container-partie-1-2">
	<div class="container-partie1">
	<div class="container1">

		{% if capture.status == 'validated' %}
		<p class="pastille-validé">
			Validée
		</p>
		{% endif %}

	<div>
    {% if capture.image is not null %}
		<img class="image-page-observation"src="{{ asset('uploads/bird/' ~ capture.image.filename) }}" alt="" height="150">
                {% else %}
					<img src="{{ asset('default/bird_default.jpg') }}" alt="">

    {% endif %}
	</div>
	</div>
	</div>

	<div class="container-partie2">
	<div class="container2">
	<h1>
		<a href="{{ path('bird', {id: capture.bird.id}) }}">
			{% if capture.bird.vernacularname == false %}
				{{ capture.bird.validname }}
			{% else %}
				{{ capture.bird.vernacularname }} - {{ capture.bird.validname }}
			{% endif %}
		</a>
	</h1>
	<p>{{ capture.createdDate|date('d/m/Y') }}</p>
	<p>{{ capture.address }}, {{ capture.zipcode }}, {{ capture.city }}</p>
	<p class="information-page-ob">Informations :</p>
	<p class="message-observation">{{ capture.content }}</p>
	</div>
	</div>
	</div>
	</div>

	<div class="container-partie3">
	<p>
		Publié par :
		{% if capture.user.avatar == null %}
			{{ capture.user.username }}
		{% else %}
			<img src="{{ asset('uploads/avatar/' ~ capture.user.avatar.filename ) }}" alt="" height="80">
		{% endif %}
	</p>
	{% if 'particular' in capture.user.roles %}
		<p>Validé par :
			{% if capture.validatedBy.avatar == null %}
				{{ capture.validatedBy.username }}
			{% else %}
                {{ capture.validatedBy.username }}
				<img src="{{ asset('uploads/avatar/' ~ capture.validated_by.avatar.filename) }}" alt="" height="80">
			{% endif %}
		</p>
	{% endif %}

	<p id="numbercomments" data-number={{ numberOfCaptureComments }}>
		{% if numberOfCaptureComments == 1 %}
			Commentaire :
		{% elseif numberOfCaptureComments > 1 %}
			Commentaires :
		{% else %}
			Soyez le premier à commenter !
		{% endif %}
	</p>
	<section id="comments">
		<ul id="comment">
		</ul>
	</section>
        {% if is_granted('ROLE_USER') %}
            {{ form_start(form, {'attr': {'class': "form-page-observation"}}) }}
            {{ form_errors(form) }}
            {{ form_widget(form) }}
			<button type="submit">Commenter</button>
            {{ form_end(form) }}
        {% endif %}
	</div>
	</div>
	</div>
{% endblock %}

{% block mapJavascripts %}
	{{ parent() }}
	<script type="text/javascript" src="{{ asset('javascript/maps/showcapturemap.js') }}"></script>
{% endblock %}
{% block paginationJavascripts %}
	{{ parent() }}
	<script type="text/javascript" src="{{ asset('javascript/comments/commentspagination.js') }}"></script>
{% endblock %}
   

templates/capture/show_captures.html.twig
{% extends "layout.html.twig" %}

{% block title %} Observations {% endblock %}
{% block mapStylesheets %} 
	{{ parent() }}
	<style type="text/css">
			#map{ /* la carte DOIT avoir une hauteur sinon elle n'apparaît pas */
				height:250px;
				position: sticky !important;
			}
		</style>
{% endblock %}

{% block body %}
	<div id="map">
	</div>
    <form action="{{ path('captures') }}" method="post" class="f-observation-m">
		<select name="bird" id="bird">
			<option disabled selected value="" class="bird">Oiseau</option>
            {% for bird in birds %}
				<option value="{% if bird.vernacularname == false %}{{ bird.validname|lower  }} {% else %} {{ bird.vernacularname|lower }}{% endif %}">{% if bird.vernacularname == false %}{{ bird.validname }} {% else %} {{ bird.vernacularname }} - {{ bird.validname }}{% endif %}</option>
            {% endfor %}
		</select>
		<select name="region" id="region">
			<option disabled selected value="">Région</option>
            {% for region in regions %}
				<option value="{{ region.nom|lower }}">{{ region.nom }}</option>
            {% endfor %}
		</select>
		<button type="submit" class="btn-r-observation">Rechercher</button>
	</form>
    <section class="observation-recherche">
		<div class="container-home">

		{% for capture in captures %}
		<div class="forme-observation-home">

				<div>
                {% if capture.image is not null %}
					<img src="{{ asset('uploads/bird/' ~ capture.image.filename) }}" alt="" height="150">
                {% else %}
					<img src="{{ asset('default/bird_default.jpg') }}" alt="Oiseau" height="150">
                {% endif %}
				</div>
				<div class="container-p-home">
                <div class="p-home">
				<p>
					<a href="{{ path('capture', {id: capture.id}) }}">
						{% if capture.bird.vernacularname == false %}
						{{ capture.bird.validname }}
						{% else %}
						{{ capture.bird.vernacularname }}
					</a>{% endif %}
				</p>
				<p>{{ capture.address }}, {{ capture.zipcode }}, {{ capture.city }}</p>
				<p>{{ capture.createdDate|date('d/m/Y') }}</p>
				</div>
				</div>


		{% endfor %}
		</div>
		</div>


		<div class="page-div">
			<ul class="page-compte">
				{% if nbCapturesPages > 1 %}
					{% if previousPage > 0 %}
					<p> {% if resultats is defined  %}
							<a href="{{ path('result_search_captures', {pageNumber: previousPage}) }}"> << </a> 
						{% else %}
							<a href="{{ path('captures', {pageNumber: previousPage}) }}"> << </a> 
						{% endif %}
					</p>
					{% endif %}
					{% for i in 1..nbCapturesPages %}
						{% if i == 1 or ((pageNumber - 5) < i and i < (pageNumber + 5)) or i == pageNumber %}
	   						{% if i == nbCapturesPages and pageNumber < (nbCapturesPages - 5) %}
	   							<p> ... </p>
	   						{% endif %}
							<li {% if pageNumber == i %} class="active" {% endif %}>
								{% if resultats is defined  %}
									<a href="{{ path('result_search_captures', {pageNumber: i}) }}"> {{i}} </a>
   								{% else %}
   									<a href="{{ path('captures', {pageNumber: i}) }}"> {{i}} </a>
   								{% endif %}
   							</li>
   							{% if i == 1 and pageNumber > 6 %}
   								<p> ... </p>
   							{% endif %}
	   					{% endif %}
   					{% endfor %}
    				<p>
    					{% if nextPage <= nbCapturesPages %}
    						{% if resultats is defined  %}
    							<a href="{{ path('result_search_captures', {pageNumber: nextPage}) }}"> >> </a>
    						{% else %}
    							<a href="{{ path('captures', {pageNumber: nextPage}) }}"> >> </a>
    						{% endif %}
    					{% endif %}
    				</p> 
    			{% endif %}
			</ul>
		</div>
	</section>
{% endblock %}

{% block mapJavascripts %}
	{{ parent() }}
	<script type="text/javascript" src="{{ asset('javascript/maps/showmap.js') }}"></script>
{% endblock %}
   